### ISSUE TITLE
Cache participant data

### ISSUE THREAD

**Issue by tomasr8** [indico/indico-checkin-pwa#16]
Currently, every time a user navigates to an event, regform or participant details, all data is fetched again.
This makes the UI less responsive. We should cache the data so that it's only fetched every X-minutes.
(With an option to trigger a manual refetch?)

**Comment by ThiefMaster** [comment]
I think we should always trigger a re-fetch, but show cached data (and an indicator that it's not fresh) until the new data finished loading. We could also refresh the cached data periodically while the site app is open though, but maybe that's overkill

IMHO showing stale data even though you have a perfectly fine internet connection is not acceptable - as a user I would be very annoyed about such behavior
