### ISSUE TITLE
Sound effect for a successful scan

### ISSUE THREAD

**Issue by tomasr8** [indico/indico-checkin-pwa#18]
It would be nice to have audible feedback when scanning a participant QR code.
Here's an example with some retro gaming sounds: https://github.com/tomasr8/cern-indico-check-in/tree/sound-effects

**Comment by GovernmentPlates** [comment]
I found:
* https://freesound.org/people/PaulMorek/sounds/330046/
* https://freesound.org/people/Eponn/sounds/531511/

Might also be nice to consider (just throwing this in...).

**Comment by tomasr8** [comment]
I like those! We could even make the sound customizable
